import { Providers } from "./providers";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@rainbow-me/rainbowkit/styles.css";
import "./globals.css";

import { ConnectButton } from "@rainbow-me/rainbowkit";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh-CN"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        style={{
          margin: 0,
          fontFamily: "system-ui, -apple-system, sans-serif",
        }}
      >
        <Providers>
          {/* 顶部导航栏 */}
          <nav
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              padding: "16px 24px",
              borderBottom: "1px solid #eaeaea",
              backgroundColor: "#fff",
            }}
          >
            {/* Logo / 首页链接 */}
            <Link
              href="/"
              style={{
                fontSize: "20px",
                fontWeight: "bold",
                textDecoration: "none",
                color: "#333",
              }}
            >
              DApp Demo
            </Link>

            {/* RainbowKit 钱包按钮 */}
            <ConnectButton />
          </nav>

          {/* 页面内容 */}
          <main style={{ height: "calc(100vh - 74px)" }}>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
